services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - db_data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: docker
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - app
    volumes:
      - pg_admin:/var/lib/pgadmin

networks:
  app:
    driver: bridge

volumes:
  db_data:
  pg_admin:
